baseURL: https://www.shanewasley.me
languageCode: en-us
title: Shane Wasley
paginate: 4
theme: "hugo-PaperMod"

imaging:
  quality: 100

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Shane Wasley's Design Portfolio
  description: "Shane Wasley's design portfolio site, where you can find examples of Shane's work and learn more about Shane as a designer."
  keywords: [Portfolio, Design, UX Design, Product Design, UX Research]
  author: Shane Wasley
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  disableAnchoredHeadings: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: true
  showtoc: true
  tocopen: false
  images:
    maxSize: 1440
    setSizes:
      - 480
      - 800
      - 720
    sizes: 'sizes=(max-width: 30em) 90vw, (max-width: 60em) 80vw, 1440px'
  responsiveImages: true
  convertImagesTo: "webp"

  # assets:
  #     # disableHLJS: true # to disable highlight.js
  #     # disableFingerprinting: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  #label:
  #  text: ""
  #  icon: /images/logo.svg
  #  iconHeight: 50
  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hello \U0001F44B"
    Content:
      Welcome to my portfolio site, where you can find examples of my work and learn more about me as a designer.
      If you want details about my work history, please visit my Linkedin [profile](https://www.linkedin.com/in/shanewasley/).

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #     URL: "https://github.com/<path_to_repo>/content"
  #     Text: "Suggest Changes" # edit text
  #     appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/about-me/
      weight: 30

taxonomies:
  category: categories
  tag: tags
  series: series

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
# goldmark:
#     renderer:
#         unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
